"""Short exclusive barrier for media protection publication and cleanup.

The barrier does not cover HTTP requests or serialize different recording
uploads. A cleanup cannot race the initial durable journal/start reservation.
"""
from functools import wraps
from contextlib import contextmanager, ExitStack
import hashlib
import os
from pathlib import Path
import re
import stat
import time
import math
from . import config
from .operation_lease import operation_lease, OperationLeaseError

@contextmanager
def media_state_lease(*, wait=False, timeout_s=2.0):
    # Different recordings may publish short checkpoints simultaneously.
    # Wait only for this local critical section; HTTP and SID ownership never
    # use this wait. Cleanup keeps its nonblocking, fail-closed behavior.
    if (type(timeout_s) not in (int, float) or not math.isfinite(timeout_s)
            or timeout_s < 0):
        raise ValueError('Tempo de espera da operação local inválido.')
    deadline = time.monotonic() + timeout_s
    stack = ExitStack()
    while True:
        try:
            stack.enter_context(operation_lease(config.DATA_DIR/'.media-lifecycle.lock'))
            break
        except OperationLeaseError:
            if not wait or time.monotonic() >= deadline:
                stack.close()
                raise
            time.sleep(0.01)
    try:
        yield
    finally:
        stack.close()

def cleanup_operation(fn):
    @wraps(fn)
    def guarded(*args,**kwargs):
        with media_state_lease():
            return fn(*args,**kwargs)
    return guarded


def _managed_path(path, roots):
    """Confine both lexical and resolved paths without following reparses."""
    raw = Path(path).absolute()
    for root in roots:
        base = Path(root).absolute()
        if not raw.is_relative_to(base):
            continue
        for current in (raw, *raw.parents):
            if current.exists() or current.is_symlink():
                info = current.lstat()
                if (current.is_symlink() or getattr(info, 'st_file_attributes', 0)
                        & getattr(stat, 'FILE_ATTRIBUTE_REPARSE_POINT', 0x400)):
                    raise ValueError('Atalho de diretório impede a limpeza de mídia.')
            if current == base:
                break
        resolved, resolved_root = raw.resolve(), base.resolve()
        if resolved.is_relative_to(resolved_root):
            return resolved, resolved_root
    raise ValueError('Arquivo fora das raízes de mídia gerenciada.')


def _managed_marker(path):
    return path.with_name(path.name + '.managed.json')


def _managed_fingerprint(path, algorithm='sha256'):
    before = path.stat()
    if not stat.S_ISREG(before.st_mode):
        raise ValueError('Mídia gerenciada deve ser um arquivo regular.')
    sha256 = hashlib.sha256()
    expected = sha256 if algorithm == 'sha256' else hashlib.sha1()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            sha256.update(block)
            if expected is not sha256:
                expected.update(block)
    after = path.stat()
    if (before.st_size, before.st_mtime_ns, before.st_ino) != (
            after.st_size, after.st_mtime_ns, after.st_ino):
        raise ValueError('Mídia alterada durante a verificação.')
    return before.st_size, sha256.hexdigest(), expected.hexdigest()


def record_managed_media(path, *, root, provider, role, expected_digest, algorithm='sha256'):
    """Bind verified provider/generated bytes to cleanup ownership.

    A filename alone is never ownership. Callers provide the digest established
    by the official download or productive encoder, and this boundary verifies
    it before publishing a removable-media marker.
    """
    from .atomic_io import save_json
    if (provider not in {'ego4d', 'nymeria', 'holoassist'} or not isinstance(role, str)
            or not role or algorithm not in {'sha256', 'sha1'}
            or not isinstance(expected_digest, str)
            or not re.fullmatch('[0-9a-f]{' + str(64 if algorithm == 'sha256' else 40) + '}', expected_digest)):
        raise ValueError('Identidade de mídia gerenciada inválida.')
    resolved, base = _managed_path(path, (root,))
    marker, _ = _managed_path(_managed_marker(resolved), (base,))
    before = resolved.stat()
    size, digest, actual_expected = _managed_fingerprint(resolved, algorithm)
    if actual_expected != expected_digest:
        raise ValueError('Hash de mídia gerenciada diverge da origem verificada.')
    value = {'version': 1, 'provider': provider, 'role': role, 'root': str(base),
             'relative_path': str(resolved.relative_to(base)), 'bytes': size,
             'sha256': digest, 'source_digest': expected_digest, 'source_algorithm': algorithm}
    # Hashing a large original must not monopolize the short publication
    # barrier used by account journals. Publish only after rechecking the file
    # under that barrier; a concurrent removal/change cannot gain ownership.
    with media_state_lease(wait=True, timeout_s=30.0):
        _managed_path(resolved, (base,))
        _managed_path(marker, (base,))
        current = resolved.stat()
        if (before.st_size, before.st_mtime_ns, before.st_ino) != (
                current.st_size, current.st_mtime_ns, current.st_ino):
            raise ValueError('Mídia alterada antes de registrar sua propriedade.')
        save_json(marker, value)
    return value


def _managed_binding(path, roots):
    from .atomic_io import load_json_state
    resolved, base = _managed_path(path, roots)
    marker, _ = _managed_path(_managed_marker(resolved), (base,))
    if not resolved.is_file() or not marker.is_file():
        return None
    value = load_json_state(marker, None)
    if (type(value) is not dict or type(value.get('version')) is not int or value['version'] != 1
            or value.get('provider') not in {'ego4d', 'nymeria', 'holoassist'}
            or not isinstance(value.get('role'), str) or not value['role']
            or not isinstance(value.get('root'), str) or not Path(value['root']).is_absolute()
            or type(value.get('bytes')) is not int or value['bytes'] < 0
            or not isinstance(value.get('sha256'), str)
            or not re.fullmatch('[0-9a-f]{64}', value['sha256'])):
        return None
    owned_root = Path(value['root'])
    if not owned_root.is_relative_to(base):
        return None
    owned_path, owned_root = _managed_path(resolved, (owned_root,))
    if value.get('relative_path') != str(owned_path.relative_to(owned_root)):
        return None
    size, digest, _ = _managed_fingerprint(resolved)
    if size != value['bytes'] or digest != value['sha256']:
        return None
    return resolved, marker, value


def managed_media_paths(paths, *, allowed_roots):
    """Return only unchanged, owned regular files; preserve ambiguous entries."""
    result = []
    for path in dict.fromkeys(Path(value) for value in paths):
        try:
            binding = _managed_binding(path, allowed_roots)
        except (OSError, ValueError):
            continue
        if binding is not None:
            result.append(binding[0])
    return result


@cleanup_operation
def cleanup_managed_media(paths, *, allowed_roots, protected_paths=(), protection=None):
    """Release provider bytes after their consumers finish, preserving retries.

    Journal validation precedes any deletion. Ownership, all journal digests,
    and explicit in-flight consumers are checked while publication is excluded.
    A corrupt journal is an error; it cannot become an empty protection list.
    """
    if protection is None:
        from .recovery import media_cleanup_protection
        protection = media_cleanup_protection()
    guards = {Path(value).resolve() for value in (*protection['paths'], *protected_paths)}
    hashes = protection['sha256']
    result = {'files': 0, 'bytes': 0, 'errors': [], 'skipped': 0, 'removed_paths': []}
    for raw in dict.fromkeys(Path(value) for value in paths):
        try:
            binding = _managed_binding(raw, allowed_roots)
            if binding is None:
                result['skipped'] += 1
                continue
            path, marker, value = binding
            if (any(guard == path or guard in path.parents or guard == marker
                    or guard in marker.parents for guard in guards)
                    or value['sha256'] in hashes):
                result['skipped'] += 1
                continue
            path.unlink()
            result['files'] += 1
            result['bytes'] += value['bytes']
            result['removed_paths'].append(str(path))
            marker_size = marker.stat().st_size
            marker.unlink()
            result['files'] += 1
            result['bytes'] += marker_size
        except (OSError, ValueError) as exc:
            result['skipped'] += 1
            result['errors'].append(f'{raw.name}: {type(exc).__name__}')
    return result
