cmake_minimum_required(VERSION 3.21)
project(QMoneyNativeTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
if(WIN32)
  add_executable(updater_transaction updater_transaction.cpp)
  target_link_libraries(updater_transaction PRIVATE shell32)
  add_test(NAME updater_transaction COMMAND updater_transaction)
endif()
