#pragma once
#include <functional>

#include "ApiClient.hpp"
#include "UpdateManager.hpp"

#include <QJsonArray>
#include <QHash>
#include <QJsonObject>
#include <QMainWindow>
#include <QProcess>
#include <QSet>
#include <QTimer>

class QCheckBox;
class QComboBox;
class QLabel;
class QLineEdit;
class QListWidget;
class QMenu;
class QBoxLayout;
class QResizeEvent;
class OperationTrack;
class OperationTimeline;
class QPlainTextEdit;
class QProgressBar;
class QPushButton;
class QSpinBox;
class QDoubleSpinBox;
class QStackedWidget;
class QTableWidget;
class QTabWidget;
class QWidget;

namespace oclero::qlementine { class QlementineStyle; }

class MainWindow final : public QMainWindow {
  Q_OBJECT

public:
  explicit MainWindow(oclero::qlementine::QlementineStyle* style,
                      QWidget* parent = nullptr, bool startServices = true);
  ~MainWindow() override;

protected:
  void closeEvent(QCloseEvent* event) override;
  void resizeEvent(QResizeEvent* event) override;

private:
  friend class OperationPreview;
  QWidget* buildHomePage();
  QWidget* buildReadinessPage();
  QWidget* buildIntegrationsPage();
  QWidget* buildCampaignPage();
  QWidget* buildAcceleratorPage();
  QWidget* buildAccountsPage();
  QWidget* buildBalancesPage();
  QWidget* buildHistoryPage();
  QWidget* buildBannedPage();
  void loadBanned();
  QTableWidget* _bannedTable{};
  QPushButton* _bannedRefresh{};
  QLabel* _bannedState{};
  QTimer _bannedPoll;
  bool _bannedPolling{false};
  QWidget* pageShell(const QString& title, const QString& subtitle, QWidget* body);
  QWidget* card(const QString& title, QWidget* content = nullptr);
  QWidget* metric(const QString& value, const QString& caption, QLabel** valueLabel);
  QPushButton* primaryButton(const QString& text);
  void buildShell();
  void applyStructuralStyle(bool dark);
  void setDarkTheme(bool dark);
  void checkForUpdates(bool interactive = false);
  void installUpdate(const QString& packagePath, const QString& verifiedSha256);

  void startBackend();
  void stopBackend();
  void beginCampaignDrain();
  void completeCampaignDrain();
  void pollCampaignClose();
  bool launchPendingUpdate();
  void restartBackend();
  void probeBackend();
  void setBackendReady(bool ready, const QString& message = {});
  void navigate(int index);
  void refreshCurrentPage();
  void showError(const QString& title, const QString& error);
  void showAccountIssues(const QString& title, const QStringList& blockers,
                         const QJsonArray& issues, std::function<void()> continueAction = {});
  void submitCampaign(QJsonObject body);
  void preflightCampaign(QJsonObject body, QStringList selectedAccountNames);
  void pollCampaignPreflight(QJsonObject body, QStringList selectedAccountNames, const QString& path);
  void chooseOriginalCapture();
  void preflightOriginalCapture(QJsonObject body);
  void submitOriginalCapture(QJsonObject body, QJsonObject reviewedSummary);
  void setStatus(const QString& text);

  void loadHome();
  void openMailCleanup();
  void openCommandPalette();
  void openRecovery();
  QString _pendingAccountFocus;
  QString _pendingHistoryFocus;
  void renderOperation(const QJsonObject& snapshot);
  void refreshOperation();
  void loadOperationBalance();
  void operationUnavailable(const QString& error);
  void filterOperationRows();
  void showOperationAccount();
  void stopOperation();
  void loadReadiness();
  void loadIntegrations();
  void saveEgo4dIntegration();
  void testEgo4dIntegration();
  void prepareEgo4dCatalog();
  void saveHostingerIntegration();
  void testHostingerIntegration();
  void selectHostingerIntegration(int index);
  void removeHostingerIntegration();
  void chooseLibrary();
  void exportDiagnostics();
  void loadCampaignData();
  void updateCampaignAccountCount();
  void drawCampaignAccounts();
  void loadCampaignBalances();
  void saveCampaignDraft();
  void loadTasks();
  void startCampaign();
  void updateCampaignActions();
  bool campaignResetBlocked() const;
  void resetCampaigns();
  void invalidateCampaignUiRequests();
  bool clearCampaignUiAfterReset();
  void pollCampaign();
  bool rememberCampaignStart(const QString& identity);
  void clearCampaignStart();
  void lookupCampaignStart();
  void setCampaignIndicator(const QString& title, const QString& detail, const QString& state, bool busy = false);
  void pollCampaignPreviews();
  void resetCampaignPreviewDisplay();
  void loadAccelerator();
  void loadLocalMediaLibrary(bool refresh = false);
  void localMediaFiltersChanged();
  QString localMediaPath(bool videoOnly = false) const;
  void updateLocalMediaActions();
  void loadPreparedLibrary(bool refresh = false);
  void preparedLibraryFiltersChanged();
  QString preparedLibraryVideoPath(const QString& role) const;
  void updatePreparedLibraryActions();
  void invalidatePreparedLibrary();
  void openEgoLibrary();
  void startAccelerator();
  void loadAccounts();
  void renderAccounts(const QJsonArray& accounts);
  void filterAccounts();
  void showAccountDetails(const QJsonObject& account);
  void beginRegistrationPolling();
  void resumeAccount(const QString& email);
  QWidget* credentialCopyActions(const QString& email, bool hasPassword, bool banned = false);
  void showSavedAccountCredentials(const QString& email, const QString& password);
  void removeAccount(const QString& email, std::function<void()> onRemoved = {});
  void checkAllAccounts();
  void addAccount(bool registerNew);
  void importAccounts();
  void exportAccounts(bool selectedOnly);
  void loadBulkRegisterDomains();
  void loadRegistrationProxies(bool selectAuto = false);
  void importRegistrationProxiesFile(const QString& path);
  QComboBox* _accountProxy{};
  QComboBox* _bulkRegisterProxy{};
  QPushButton* _accountProxyImport{};
  QPushButton* _bulkProxyImport{};
  bool _registrationProxiesReady{false};
  int _registrationProxiesRevision{0};
  void checkBulkRegisterDomain();
  void startBulkRegister();
  void pollBulkRegister();
  void openWebmail();
  void startOrgMigration();
  void pollOrgMigration();
  void showOrgMigrationReport();
  QTimer _orgMigrationPoll;
  bool _orgMigrationRunning{false};
  bool _orgMigrationPolling{false};
  bool _accountTransferBusy{false};
  QJsonObject _orgMigrationSnapshot;

  QComboBox* _bulkRegisterDomain{};
  QSpinBox* _bulkRegisterCount{};
  QCheckBox* _bulkRegisterUseReferral{};
  QPushButton* _bulkRegisterStart{};
  QPushButton* _bulkRegisterStop{};
  QProgressBar* _bulkRegisterProgress{};
  QLabel* _bulkRegisterStatus{};
  QLabel* _bulkRegisterWebmail{};
  QTableWidget* _bulkRegisterTable{};
  QJsonArray _bulkRegisterResults;
  QTimer _bulkRegisterPoll;
  bool _bulkRegisterPolling{false};
  bool _bulkRegisterStarting{false};
  bool _bulkRegisterRequestInFlight{false};
  int _bulkRegisterDomainsRevision{0};
  int _bulkRegisterPreflightRevision{0};
  QPushButton* _accountsMigrate{};
  QPushButton* _migrationReport{};
  QLabel* _migrationStatus{};
  QPushButton* _accountsImport{};
  QPushButton* _accountsExport{};
  QPushButton* _accountsExportSelected{};
  void setAccountTransferBusy(bool busy);
  void loadBalances();
  void refreshBalanceAccounts(const QJsonArray& emails = {});
  void showBalanceDetails(const QString& email);
  void disableWalletActions();
  void applyBalanceFilter();
  void showWithdrawalReport(const QJsonObject& bulk);
  void configureCrowtadoAccess(const QString& email);
  void loadHistory();

  QString usdMoney(qint64 cents) const;
  QString brlMoney(qint64 usdCents, double usdBrlRate) const;
  QString friendlyDate(const QString& iso) const;
  QString encoded(const QString& value) const;
  oclero::qlementine::QlementineStyle* _style{};
  ApiClient _api;
  QHash<QString, QJsonObject> _accountChecks;
  UpdateManager _updates;
  QProcess _backend;
  QString _packagedServiceExecutable;
  QTimer _backendProbe;
  QTimer _campaignPoll;
  QTimer _previewPoll;
  QTimer _taskReload;
  QTimer _balancePoll;
  bool _balancePolling{};
  QTimer _cachePoll;
  int _probeAttempts{};
  int _probeGeneration{};
  bool _probeInFlight{};
  int _backendRestarts{};
  bool _backendReady{};
  bool _runtimeChecked{};
  bool _closing{};
  bool _campaignClosePending{};
  bool _campaignCloseReady{};
  bool _campaignCloseInFlight{};
  QTimer _campaignClosePoll;
  bool _campaignRestartPending{};
  bool _campaignTransitionCommitted{};
  bool _campaignExitRequested{};
  bool _resumeOperationPoll{};
  QString _pendingLibraryRoot;
  QString _pendingUpdatePackage;
  QString _pendingUpdateSha256;
  bool _restartingBackend{};

  QListWidget* _navigation{};
  QStackedWidget* _pages{};
  QLabel* _backendState{};
  QLabel* _status{};
  QPushButton* _themeButton{};
  QPushButton* _updateButton{};

  QLabel* _homeAccounts{};
  QMenu* _settingsMenu{};
  QBoxLayout* _operationColumns{};
  QBoxLayout* _campaignSelectionColumns{};
  QBoxLayout* _libraryColumns{};
  QWidget* _operationInspector{};
  QList<QBoxLayout*> _pageHeaders;
  QList<QWidget*> _headerIdentities;
  QTimer _operationPoll;
  bool _operationPolling{false};
  int _operationGeneration{0};
  int _operationBackendGeneration{0};
  int _operationBalanceGeneration{0};
  qint64 _operationBalanceReadAt{0};
  bool _operationAvailable{false};
  QString _operationControlError;
  QJsonObject _operationSnapshot;
  QJsonArray _homeAccountSnapshot;
  QLabel* _operationNotice{};
  QLabel* _operationVisible{};
  QWidget* _operationIdleSpace{};
  QLineEdit* _operationSearch{};
  QCheckBox* _operationAttention{};
  QPushButton* _operationRefresh{};
  QPushButton* _operationCreate{};
  QPushButton* _operationStop{};
  QPushButton* _operationDetails{};
  QTableWidget* _operationTable{};
  OperationTrack* _operationTrack{};
  OperationTimeline* _operationTimeline{};
  QLabel* _operationTotal{};
  QWidget* _operationProgressRow{};
  QLabel* _operationBalance{};
  QLabel* _operationBalanceNote{};
  QLabel* _operationContextTitle{};
  QPushButton* _operationPause{};
  QLabel* _operationLive{};
  bool _operationPauseRequested{false};
  bool _operationPausePending{false};
  QLabel* _operationStages{};
  QLabel* _operationFeed{};
  QLabel* _operationEmpty{};
  QPushButton* _homeNextAction{};
  QLabel* _homeAccountStep{};
  QLabel* _homeRecent{};
  QLabel* _homeSync{};
  int _homeDestination{1};
  int _homeGeneration{0};
  QLabel* _homeCampaigns{};
  QLabel* _homeSuccess{};
  QLabel* _homePulseTitle{};
  QLabel* _homePulseBody{};
  QProgressBar* _homePulseProgress{};

  QLabel* _readinessHeadline{};
  QLabel* _readinessSummary{};
  QProgressBar* _readinessProgress{};
  QTableWidget* _readinessTable{};
  QLabel* _libraryPath{};
  QLabel* _libraryUsage{};
  QPushButton* _readinessRefresh{};
  QPushButton* _libraryChoose{};
  QPushButton* _diagnosticsExport{};
  QPushButton* _repairInstall{};
  QString _currentLibraryRoot;

  QLabel* _integrationsHeadline{};
  QLabel* _integrationsSummary{};
  QLabel* _ego4dStatus{};
  QLabel* _ego4dCatalog{};
  class QLineEdit* _ego4dAccessKey{};
  class QLineEdit* _ego4dSecretKey{};
  class QLineEdit* _ego4dSessionToken{};
  class QLineEdit* _ego4dRegion{};
  QPushButton* _ego4dSave{};
  QPushButton* _ego4dTest{};
  QPushButton* _ego4dPrepare{};
  bool _ego4dCatalogPreparing{};
  QLabel* _hostingerStatus{};
  class QComboBox* _hostingerProfile{};
  class QLineEdit* _hostingerToken{};
  QPushButton* _hostingerRemove{};
  QPushButton* _hostingerSave{};
  QPushButton* _hostingerTest{};
  QLabel* _holoIntegrationStatus{};
  QLabel* _runtimeIntegrationStatus{};
  QLabel* _integrationSecurity{};

  QComboBox* _dataset{};
  QComboBox* _contentMode{};
  QListWidget* _campaignAccounts{};
  QLineEdit* _campaignAccountSearch{};
  QComboBox* _campaignAccountMode{};
  QSpinBox* _campaignAccountCount{};
  QPushButton* _campaignDrawAccounts{};
  QLabel* _campaignAccountSelection{};
  QLabel* _campaignBalanceHint{};
  QJsonObject _campaignBalances;
  bool _campaignBalancesLoaded{};
  int _campaignBalanceRequestId{};
  QListWidget* _campaignTasks{};
  QSet<QString> _campaignSelectedTaskIds;
  bool _campaignTaskSelectionTouched{};
  QSet<QString> _campaignDraftAccounts;
  bool _campaignDraftLoaded{};
  int _campaignDraftQuantity{1};
  QTimer _campaignDraftSave;
  QDoubleSpinBox* _targetHours{};
  QSpinBox* _minDuration{};
  QSpinBox* _maxDuration{};
  QComboBox* _delayMode{};
  QComboBox* _accountWorkers{};
  QSpinBox* _delaySeconds{};
  QCheckBox* _cleanupAfter{};
  QCheckBox* _activeHours{};
  QSpinBox* _hourStart{};
  QSpinBox* _hourEnd{};
  QPushButton* _campaignStart{};
  QPushButton* _campaignOriginal{};
  bool _campaignOriginalDialogPending{};
  QPushButton* _campaignStop{};
  QPushButton* _campaignReset{};
  QProgressBar* _campaignProgress{};
  QTabWidget* _campaignTabs{};
  QWidget* _campaignIndicator{};
  QWidget* _campaignIndicatorIcon{};
  QLabel* _campaignIndicatorMetric{};
  QLabel* _campaignIndicatorTitle{};
  QLabel* _campaignIndicatorDetail{};
  QProgressBar* _campaignIndicatorProgress{};
  QLabel* _campaignStage{};
  QLabel* _campaignCurrent{};
  QLabel* _campaignStats{};
  QWidget* _campaignPreviewPanel{};
  QLabel* _campaignPreviewStage{};
  QLabel* _campaignPreviewDetail{};
  QLabel* _campaignPreviewStats{};
  QLabel* _campaignReceiptStats{};
  QProgressBar* _campaignPreviewProgress{};
  QPlainTextEdit* _campaignFeed{};
  QJsonArray _taskRecords;
  int _taskLoadGeneration{};
  bool _taskRequestPending{};
  bool _cacheCatalogPending{};
  bool _cacheStartPending{};
  int _lastCampaignSeq{};
  QString _previewLogName;
  bool _previewCheckActive{};
  bool _campaignActive{};
  bool _campaignStartPending{};
  bool _campaignPreflightPending{};
  bool _campaignStopPending{};
  bool _campaignResetPending{};
  bool _campaignStartUncertain{};
  bool _campaignStartLookupInFlight{};
  QString _campaignRequestedPreflight;
  bool _campaignPollInFlight{};
  int _campaignPollRevision{};
  quint64 _campaignUiEpoch{};
  bool _recoveryCommandPending{};
  bool _campaignResetRunnerBusy{};

  QComboBox* _cacheProvider{};
  quint64 _cacheRequestId{};
  QString _cacheRequestKey;
  QString _cacheInFlightKey;
  QJsonObject _cacheCatalogSnapshot;
  bool _cacheBudgetLoaded{};
  QLabel* _cacheTaskLabel{};
  QLabel* _cacheProviderHelp{};
  QLabel* _cacheTaskHelp{};
  QLabel* _cacheBudgetHelp{};
  QLabel* _cacheDiskHelp{};
  QLabel* _cacheLimitHelp{};
  QComboBox* _cacheTask{};
  QSpinBox* _cacheLimit{};
  QLabel* _cacheBudgetLabel{};
  QSpinBox* _cacheBudget{};
  QSpinBox* _cacheReserve{};
  QSpinBox* _cacheMinimum{};
  QSpinBox* _cacheMaximum{};
  QLabel* _cacheState{};
  QLabel* _cacheNumbers{};
  QLabel* _cacheLastRun{};
  QProgressBar* _cacheProgress{};
  QPushButton* _cacheStart{};
  QPushButton* _cacheStop{};
  QTableWidget* _preparedTable{};
  QTabWidget* _libraryTabs{};
  QLabel* _libraryStorageSummary{};
  QLabel* _libraryBase{};
  QPushButton* _libraryOpenFolder{};
  QTableWidget* _localMediaTable{};
  QLineEdit* _localMediaQuery{};
  QComboBox* _localMediaProvider{};
  QComboBox* _localMediaKind{};
  QLabel* _localMediaSummary{};
  QLabel* _localMediaCount{};
  QPushButton* _localMediaRefresh{};
  QPushButton* _localMediaPrevious{};
  QPushButton* _localMediaNext{};
  QPushButton* _localMediaOpen{};
  QPushButton* _localMediaCopy{};
  QTimer _localMediaPoll;
  quint64 _localMediaRequestId{};
  QString _localMediaRequestKey;
  QString _localMediaInFlightKey;
  QString _localMediaRefreshNonce;
  QString _localMediaRoot;
  int _localMediaOffset{};
  bool _localMediaVerified{};
  QLineEdit* _preparedQuery{};
  QComboBox* _preparedState{};
  QSpinBox* _preparedMinimum{};
  QSpinBox* _preparedMaximum{};
  QLabel* _preparedSummary{};
  QLabel* _preparedCount{};
  QPushButton* _preparedRefresh{};
  QPushButton* _preparedPrevious{};
  QPushButton* _preparedNext{};
  QPushButton* _preparedOpenNative{};
  QPushButton* _preparedOpenSource{};
  QPushButton* _preparedCopy{};
  QTimer _preparedPoll;
  quint64 _preparedRequestId{};
  QString _preparedRequestKey;
  QString _preparedInFlightKey;
  QString _preparedRefreshNonce;
  QString _preparedLibraryRoot;
  int _preparedOffset{};
  bool _preparedVerified{};
  bool _preparedRefreshPending{};

  QTableWidget* _accountsTable{};
  QLineEdit* _accountsSearch{};
  QCheckBox* _accountsAttention{};
  QLabel* _accountsSummary{};
  QJsonArray _accountsSnapshot;
  int _accountsRevision{0};
  bool _accountsAvailable{false};
  bool _accountConnecting{false};
  bool _accountsCheckRunning{false};
  QSpinBox* _accountBirthMonth{};
  QSpinBox* _accountBirthYear{};
  QComboBox* _accountGender{};
  QCheckBox* _accountUseReferral{};
  class QLineEdit* _accountEmail{};
  class QLineEdit* _accountPassword{};
  QPushButton* _accountAdd{};
  QPushButton* _accountRegister{};
  QPushButton* _accountsCheckAll{};

  QTableWidget* _balancesTable{};
  QLabel* _balancesState{};
  QLabel* _balancesWithdrawReceipt{};
  QPushButton* _balancesRefresh{};
  QPushButton* _balancesRefreshNeeded{};
  QLineEdit* _balancesSearch{};
  QCheckBox* _balancesOnlyAvailable{};
  QCheckBox* _balancesOnlyPending{};
  QLabel* _balancesFilterState{};
  QPushButton* _balancesWithdrawAll{};
  QPushButton* _balancesWiseCleanup{};
  QPushButton* _balancesPayoutMethod{};
  QPushButton* _balancesWithdrawHistory{};
  QPushButton* _balancesExport{};
  QJsonObject _balancesSnapshot;
  QJsonObject _lastWithdrawBulk;
  bool _bulkWithdrawAwaitingResult{};
  bool _payoutMethodAwaitingResult{};
  QLabel* _balancesApprovedUsd{};
  QLabel* _balancesApprovedBrl{};
  QLabel* _balancesPendingUsd{};
  QLabel* _balancesPendingBrl{};
  QLabel* _balancesTotalsNote{};
  QLabel* _balancesExchange{};
  QLabel* _balancesTransitUsd{};
  QLabel* _balancesHoldUsd{};
  QLabel* _balancesCoverage{};
  QProgressBar* _balancesProgress{};
  QPushButton* _balancesStop{};
  QCheckBox* _walletMonitoring{};
  QComboBox* _walletMonitorInterval{};
  QLabel* _walletMonitorState{};
  QTimer _walletMonitorTimer;
  bool _balanceStarting{};
  bool _walletSnapshotHealthy{};
  int _walletRequestEpoch{};

  QTableWidget* _historyTable{};
  QPushButton* _historyVerifyPreviews{};
  bool _historyVerifyPending{};
  QPlainTextEdit* _historyDetail{};
  QTableWidget* _historyEvidence{};
};
